#+STARTUP:indent
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="css/styles.css"/>
#+HTML_HEAD_EXTRA: <link href='http://fonts.googleapis.com/css?family=Ubuntu+Mono|Ubuntu' rel='stylesheet' type='text/css'>
#+HTML_HEAD_EXTRA: <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js" type="text/javascript"></script>
#+HTML_HEAD_EXTRA: <script src="js/navbar.js" type="text/javascript"></script>
#+OPTIONS: f:nil author:nil num:1 creator:nil timestamp:nil toc:nil

#+TITLE: Cryptography
#+AUTHOR: Marc Scott

#+BEGIN_HTML
  <div class="github-fork-ribbon-wrapper left">
    <div class="github-fork-ribbon">
      <a href="https://github.com/MarcScott/8-CS-Cryptography">Fork me on GitHub</a>
    </div>
  </div>
<div id="stickyribbon">
    <ul>
      <li><a href="1_Lesson.html">Week1</a></li>
      <li><a href="2_Lesson.html">Week2</a></li>
      <li><a href="3_Lesson.html">Week3</a></li>
      <li><a href="4_Lesson.html">Week4</a></li>
      <li><a href="5_Lesson.html">Week5</a></li>
      <li><a href="6_Lesson.html">Week6</a></li>
      <li><a href="assessment.html">Assessment</a></li>

    </ul>
  </div>
#+END_HTML
* COMMENT Use as a template
:PROPERTIES:
:HTML_CONTAINER_CLASS: activity
:END:
** Learn It
:PROPERTIES:
:HTML_CONTAINER_CLASS: learn
:END:

** Research It
:PROPERTIES:
:HTML_CONTAINER_CLASS: research
:END:

** Design It
:PROPERTIES:
:HTML_CONTAINER_CLASS: design
:END:

** Build It
:PROPERTIES:
:HTML_CONTAINER_CLASS: build
:END:

** Test It
:PROPERTIES:
:HTML_CONTAINER_CLASS: test
:END:

** Run It
:PROPERTIES:
:HTML_CONTAINER_CLASS: run
:END:

** Document It
:PROPERTIES:
:HTML_CONTAINER_CLASS: document
:END:

** Code It
:PROPERTIES:
:HTML_CONTAINER_CLASS: code
:END:

** Program It
:PROPERTIES:
:HTML_CONTAINER_CLASS: program
:END:

** Try It
:PROPERTIES:
:HTML_CONTAINER_CLASS: try
:END:

** Badge It
:PROPERTIES:
:HTML_CONTAINER_CLASS: badge
:END:

** Save It
:PROPERTIES:
:HTML_CONTAINER_CLASS: save
:END:

* Encryption, Decryption and Keys
:PROPERTIES:
:HTML_CONTAINER_CLASS: activity
:END:
** Learn It
:PROPERTIES:
:HTML_CONTAINER_CLASS: learn
:END:
- This module is going to focus on the science of Cryptography.
- It begin with a small research project and conclude with the creation of some simple cryptography algorithms using Python.
** Learn It
:PROPERTIES:
:HTML_CONTAINER_CLASS: learn
:END:
- Alice and Bob are sitting in a classroom and want to send notes to each other, but Eve is sitting in-between them.
- Alice can write a message onto a bit of paper, but she needs to pass it to Eve first.
- Eve can then pass the message onto Bob,  so Bob can read the message.
- Can you see how this system is insecure? Eve is easily able to read the message before passing it onto Bob.
** Try It
:PROPERTIES:
:HTML_CONTAINER_CLASS: try
:END:
- Assemble yourselves into teams of three.
- Can two of you manage to write messages to each other in such away that the third member of your group is unable to read the message?
** Badge It - Silver
:PROPERTIES:
:HTML_CONTAINER_CLASS: badge
:END:
- Write up the methods you tried to send the messages secretly.
- Use a text editor (Sublime Text for instance) and make sure you save the file with the .txt extension
** Learn It
:PROPERTIES:
:HTML_CONTAINER_CLASS: learn
:END:
- The problem is that Alice and Bob are trying to send messages in what is called =Plaintext=. Plaintext doesn't necessarily have to be text. It is just any information that is being passed between participants that can easily be read by a third party without needing any special measures. Pictures, Video, Audio as well as Text can all be described as Plaintext.
- If Alice and Bob want to communicate privately, they'll need to =Encrypt= their messages.
- =Encryption= converts information into what is known as =Ciphertext=. Ciphertext can't easily be read by Eve unless she knows the =Key= that was used to encrypt the message.
- Let's look at an example.
  - Alice tells Bob the key she is going to use prior to the lesson.
  - The key is 'I'll write the message backwards'
  - Alice then writes down her Plaintext message on a piece of paper - =I'm loving this lesson on Encryption=
  - On a second piece of paper, Alice uses her /key/ to /encrypt/ the message. =noitpyrcnE no nossel siht gnivol m'I=
  - Alice can then pass the message to Eve, who can't read it (well not quickly anyway).
  - Eve passes the message onto Bob.
  - Bob (knowing the key) can then /decrypt/ the Ciphertext and write out the Plaintext.
- Of course the encryption method shown above isn't very secure. We'd call it weak encryption.
** Research It
:PROPERTIES:
:HTML_CONTAINER_CLASS: research
:END:
- Encryption methods have been used for millennia by various people.
- Watch the video below and then answer the questions in the Badge It section.
#+BEGIN_HTML
<iframe width="420" height="315" src="https://www.youtube.com/embed/sMOZf4GN3oc" frameborder="0" allowfullscreen></iframe>
#+END_HTML
** Badge It - Gold
:PROPERTIES:
:HTML_CONTAINER_CLASS: badge
:END:
1) Why is the cipher called the Caesar Cipher?
2) Why is it known as a Substitution Cipher?
3) What is meant by the term /Shift/?
4) What is /Frequency Analysis/?
5) What is the most commonly used letter in the English language?
** Learn It
:PROPERTIES:
:HTML_CONTAINER_CLASS: learn
:END:
- Hopefully you can see that the Caesar Cipher isn't a particularly secure method of encrypting PlainText.
- To try and combat /Frequency Analysis/ the original Caesar Cipher was improved upon, by using more than one shift value.
** Research It
:PROPERTIES:
:HTML_CONTAINER_CLASS: research
:END:
- Watch this video on the =Vignere Cipher=

#+BEGIN_HTML
<iframe width="560" height="315" src="https://www.youtube.com/embed/9zASwVoshiM" frameborder="0" allowfullscreen></iframe>
#+END_HTML
** Badge It - Platinum
:PROPERTIES:
:HTML_CONTAINER_CLASS: badge
:END:
- In your own words (remember to use a text editor and the .txt extension), provide a brief description of how the Vigenere Cipher works.
- Now try decrypting this message using the Vigenere Cipher and the key of "compsci"
#+BEGIN_QUOTE
Ecyemvmt goxwpkg we cg owts mqgwb ecyemvmtg fwsp iuhddfqua we ptqcv hqawukqdqh 
#+END_QUOTE
- Keep the answer a secret so that your friends have to work it out themselves.
